### PR TITLE
SignIn to acces to the customer list

### PR DESCRIPTION
**Pull request by BlitzBanana**

### CODE REVIEW

**Comment by cyrilchapon** [comment]
Hey.

Thanks for contributing!

Please review the following so we can merge that pull request:
- Change all ES6 lambda syntaxes (`x => { }`) to ES5 `function(x){ }` syntax.
  Project is built upon standard ES5 and is not ready to accept ES6 for now (Thus the travis CI fail)
- Remove ghost modifications from the commit to keep it semantic. [This one](https://github.com/cyrilchapon/exia-secu-demo-web/pull/2/commits/611672c5402227dfaf47bd997c520c9db65eb014#diff-3c2d3a83d790ff572a51a4f2e8a86018L13) is no supposed to be part of "SignIn to Access to the customer list"
- [Optionnal] Separate commit into multiple, small and semantic commits (eg : "implemented auth API wrapper service", "Added 'customer' route & view")

Great work on wrapping Restangular promises BTW =)

**Comment by cyrilchapon** [comment]
Thanks =)

End result is ok, and PR is a good one, nearly mergeable as-is.

However, could you :
- rewrite your commit history as mentionned in gitter chat ? You can ask @ChloePrice which did the same on [cyrilchapon/exia-secu-demo-api last PR](https://github.com/cyrilchapon/exia-secu-demo-api/pull/2)
- remove [this ghost change](https://github.com/cyrilchapon/exia-secu-demo-web/pull/2/files/611672c5402227dfaf47bd997c520c9db65eb014..bccd32eed8d323f392c6b98ccac5219fcb479223#diff-3c2d3a83d790ff572a51a4f2e8a86018L13)

That would be awesome! You're pretty close to perfection =) Btw good work on making build pass on Travis CI

**Comment by BlitzBanana** [comment]
Ok, i will rewrite the commit history. The Github GUI for windows made it fail the first time, i will retry with CLI only.

**Comment by cyrilchapon** [comment]
CLI ftw !

**Comment by cyrilchapon** [comment]
Thanks for update!

Last but not least, please remove [this commit](https://github.com/cyrilchapon/exia-secu-demo-web/pull/2/commits/965990b076c0f0a7bafce0c1301685bcf162b878) (it's not needed)

> Tip: Brutal remove commit in a history => `git rebase --onto <commit-id>^ <commit-id> HEAD`
> :warning: warning, it rewrite every following commit's ids (avoid it in multi-user envs)

**Pull request merged**
